### PR TITLE
👥 Add CODEOWNERS

### LINKED ISSUE #5: Add CODEOWNER file
Owner: Tom Jemmett. Second: Yiwen Hon.

### PR DESCRIPTION
**Pull request by StatsRhian**
Closes #5

### CODE REVIEW

**Review by tomjemmett — CHANGES_REQUESTED** [review]
This is @paulseamer repo so he should be listed as code owner

**Comment by StatsRhian** [comment]
I think it was listed on our word document as being Tom and YiWen but yes I agree. I'll change now.

**Comment by StatsRhian** [comment]
@paulseamer As part of preparing to open source the NHP model, we're tidying up the public facing repos related to NHP. 

I've added you as a CODEOWNER for this repo. This effective lists you as the main maintainer of this repo and you will be suggested as a review if someone is making a PR. 

We don't imagine further work is required related to this repo, but the CODEOWNER files are useful for quickly seeing who is a main contact.

Let me know if you have any questions :)

**Review by tomjemmett — APPROVED** [review]
Awaiting @paulseamer approval, but otherwise happy

**Pull request merged**
